import type { StickerDefinition } from '@/lib/stickers'

// Positions and sizes mirror the current buycoffee.top homepage at desktop and mobile widths.
export const stickers = [
  {
    id: 'stack-overflow',
    image: '/stickers/stack-overflow.webp',
    shadow: '/stickers/stack-overflow-shadow.webp',
    imageWidth: 390,
    imageHeight: 95,
    desktop: { x: -283, y: 103, width: 130 },
    mobile: { left: 6.6, top: 23.5, width: 104 },
    rotation: -8,
    zIndex: 19,
    shadowInset: '-101.1% -24.6%',
    enterDelay: 40,
  },
  {
    id: 'openai',
    image: '/stickers/openai.webp',
    shadow: '/stickers/openai-shadow.webp',
    imageWidth: 180,
    imageHeight: 175,
    desktop: { x: -264, y: 169, width: 60 },
    mobile: { left: 6.6, top: 43, width: 48 },
    rotation: 7,
    zIndex: 21,
    shadowInset: '-54.9% -53.3%',
    enterDelay: 76,
  },
  {
    id: 'vercel',
    image: '/stickers/vercel.webp',
    shadow: '/stickers/vercel-shadow.webp',
    imageWidth: 390,
    imageHeight: 105,
    desktop: { x: 83, y: 315, width: 130 },
    mobile: { left: 65.3, top: 78.6, width: 104 },
    rotation: -10,
    zIndex: 22,
    shadowInset: '-91.4% -24.6%',
    enterDelay: 112,
  },
  {
    id: 'nezha',
    image: '/stickers/nezha.webp',
    shadow: '/stickers/nezha-shadow.webp',
    imageWidth: 180,
    imageHeight: 193,
    desktop: { x: -260, y: 11, width: 60 },
    mobile: { left: 6.6, top: 1.3, width: 48 },
    rotation: -10,
    zIndex: 23,
    shadowInset: '-49.7% -53.3%',
    enterDelay: 148,
  },
  {
    id: 'turbo',
    image: '/stickers/turbo.webp',
    shadow: '/stickers/turbo-shadow.webp',
    imageWidth: 450,
    imageHeight: 112,
    desktop: { x: -118, y: 11, width: 150 },
    mobile: { left: 32, top: -1.9, width: 120 },
    rotation: 0,
    zIndex: 24,
    shadowInset: '-85.7% -21.3%',
    enterDelay: 184,
  },
  {
    id: 'me',
    image: '/stickers/me.webp',
    shadow: '/stickers/me-shadow.webp',
    imageWidth: 252,
    imageHeight: 279,
    desktop: { x: -268, y: 251, width: 104 },
    mobile: { left: 6.6, top: 61, width: 83 },
    rotation: 0,
    zIndex: 25,
    shadowInset: '-27.8% -30.8%',
    enterDelay: 220,
  },
  {
    id: 'khalil',
    image: '/stickers/khalil.webp',
    shadow: '/stickers/khalil-shadow.webp',
    imageWidth: 339,
    imageHeight: 317,
    desktop: { x: 98, y: 167, width: 113 },
    mobile: { left: 69.6, top: 38.6, width: 90 },
    rotation: 0,
    zIndex: 26,
    shadowInset: '-30.3% -28.3%',
    enterDelay: 256,
  },
  {
    id: 'github',
    image: '/stickers/github.webp',
    shadow: '/stickers/github-shadow.webp',
    imageWidth: 376,
    imageHeight: 102,
    desktop: { x: 76, y: 98, width: 130 },
    mobile: { left: 68.5, top: 21.9, width: 104 },
    rotation: 6,
    zIndex: 27,
    shadowInset: '-90.7% -24.6%',
    enterDelay: 292,
  },
  {
    id: 'nvidia-new',
    image: '/stickers/nvidia-new.webp',
    shadow: '/stickers/nvidia-new-shadow.webp',
    imageWidth: 450,
    imageHeight: 113,
    desktop: { x: -122, y: 309, width: 150 },
    mobile: { left: 34, top: 68.2, width: 120 },
    rotation: 4,
    zIndex: 28,
    shadowInset: '-85.0% -21.3%',
    enterDelay: 328,
  },
  {
    id: 'it-crowd',
    image: '/stickers/it-crowd.webp',
    shadow: '/stickers/it-crowd-shadow.webp',
    imageWidth: 360,
    imageHeight: 182,
    desktop: { x: 90, y: 5, width: 120 },
    mobile: { left: 69.6, top: -1.3, width: 96 },
    rotation: 0,
    zIndex: 29,
    shadowInset: '-52.7% -26.7%',
    enterDelay: 364,
  },
  {
    id: 'cat',
    image: '/stickers/cat.webp',
    shadow: '/stickers/cat-shadow.webp',
    imageWidth: 198,
    imageHeight: 329,
    desktop: { x: -87, y: 99, width: 96 },
    mobile: { left: 38.8, top: 20.8, width: 77 },
    rotation: 0,
    zIndex: 30,
    shadowInset: '-20.1% -33.3%',
    enterDelay: 400,
  },
] satisfies readonly StickerDefinition[]
